const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const source = fs.readFileSync(path.join(__dirname, '../src/mods/route-filter/model.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const moduleResult = { exports: {} };
new Function('exports', 'module', compiled)(moduleResult.exports, moduleResult);
const { filteredAssetIds } = moduleResult.exports;
const asset = (id, name) => ({ id, name });
const truck = asset(1, 'Truck01');
const trailer = asset(2, 'CargoTrailer');
const hidden = asset(3, 'Car01');
const children = new Map([[1, [trailer, hidden]]]);
assert.deepEqual(filteredAssetIds([truck], children, 'truck'), [1], 'matching parent must not select hidden children');
assert.deepEqual(filteredAssetIds([truck], children, 'trailer'), [1, 2], 'displayed contextual parent and matching child are in scope');
assert.deepEqual(filteredAssetIds([truck], children, ''), [1, 2, 3], 'collapsed children remain in unfiltered group scope');
assert.deepEqual(filteredAssetIds([], children, 'missing'), [], 'no results must be a no-op');
assert.deepEqual(filteredAssetIds([asset(4, '货车')], new Map(), '货车'), [4], 'localized names remain supported');
assert.deepEqual(filteredAssetIds([truck, truck], new Map([[1, [truck]]]), ''), [1], 'duplicates/cycles cannot inflate bulk scope');
console.log('PASS: filtered bulk scope, hidden children, contextual parent, collapsed groups, empty results, localized names, deduplication.');
