const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const source = fs.readFileSync(require('node:path').join(__dirname,'../src/mods/route-filter/mapGeometry.ts'),'utf8');
const compiled = ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const result = {exports:{}}; new Function('exports','module',compiled)(result.exports,result);
const {parseMap,path} = result.exports;
const empty = parseMap(''); assert.ok(Object.values(empty.bounds).every(Number.isFinite));
const sample = parseMap('B||-30,-50;20,30\nR|12:3|5,10;20,30|2|2/4\nR|44:1|7,9|1|4/4');
assert.equal(sample.restrictions.length,2); assert.equal(sample.restrictions[0].directions,'2/4');
assert.equal(sample.restrictions[0].key,'12:3'); assert.equal(sample.restrictions[1].points.length,1);
assert.ok(sample.bounds.width >= 100 && sample.bounds.height >= 100);
assert.equal(sample.background,'M-30,-50 L20,30');
assert.equal(path([[1,2],[3,4]]),'M1,2 L3,4');
const bad = parseMap('B||NaN,2;3,4\nR|x|Infinity,0|1|2/4\nR|y|1|1|4/4');
assert.equal(bad.restrictions.length,0); assert.equal(bad.background,'');
const backgrounds = parseMap(Array.from({length:1000},(_,i)=>`B||${i},0;${i},1`).join('\n'));
assert.equal(backgrounds.background.split('M').length-1,1000);
console.log('PASS: empty/invalid map data, finite bounds, geometry, stable selection IDs, directional counts, combined background path.');
